# Argo CD Credentials for Multi-Cluster Setup
# Create these secrets in the Kargo namespace (kargo-advanced)
# on the cluster where Kargo is running

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-creds-dev
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: argocd
type: Opaque
stringData:
  # URL of the Argo CD API server in dev cluster
  # Can be:
  # - External LoadBalancer: https://argocd.dev.example.com
  # - NodePort: https://node-ip:30443
  # - Port-forward: https://localhost:8080
  # - In-cluster (if Kargo in same cluster): https://argocd-server.argocd.svc.cluster.local
  url: https://argocd.dev.example.com

  # Authentication method 1: Username/Password
  username: admin
  password: <your-dev-argocd-password>

  # Authentication method 2: Token (comment out username/password if using this)
  # token: <your-dev-argocd-auth-token>

  # Optional: Skip TLS verification (not recommended for production)
  # insecureSkipVerify: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-creds-staging
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: argocd
type: Opaque
stringData:
  url: https://argocd.staging.example.com
  username: admin
  password: <your-staging-argocd-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-creds-prod
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: argocd
type: Opaque
stringData:
  url: https://argocd.prod.example.com
  username: admin
  password: <your-prod-argocd-password>

---
# How to create these secrets via kubectl:

# Using username/password:
# kubectl create secret generic argocd-creds-dev \
#   -n kargo-advanced \
#   --from-literal=url=https://argocd.dev.example.com \
#   --from-literal=username=admin \
#   --from-literal=password=<password>
#
# kubectl label secret argocd-creds-dev \
#   -n kargo-advanced \
#   kargo.akuity.io/cred-type=argocd

# Using token (get token from Argo CD):
# TOKEN=$(argocd account generate-token --account admin)
# kubectl create secret generic argocd-creds-dev \
#   -n kargo-advanced \
#   --from-literal=url=https://argocd.dev.example.com \
#   --from-literal=token=$TOKEN
#
# kubectl label secret argocd-creds-dev \
#   -n kargo-advanced \
#   kargo.akuity.io/cred-type=argocd
